version: '3'
services:
  app:
    container_name: inosoft_app
    image: php-fpm8.0:1.0
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mongo
    networks:
      - inosoft

  web:
    container_name: inosoft_web
    image: nginx:stable-alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - inosoft

  mongo:
    container_name: inosoft_mongo
    image: mongo:4.2
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo/dev.archive:/Databases/dev.archive
      - ./data/mongo/production:/Databases/production
    command: [--auth]
    networks:
      - inosoft
      - inosoft_db

  express:
    container_name: inosoft_express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGODB_URL}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    networks:
      - inosoft_db

networks:
  inosoft:
  inosoft_db:
    